### PR TITLE
Port patch from upstream to fix FreeBSD build

### PR DESCRIPTION
**Pull request by avsej**

### CODE REVIEW

**Comment by avsej** [comment]
@ceejatec  do you know how this repo updated? Is it okay to open PR with fix?

**Comment by ceejatec** [comment]
That's fine, sure. I can also set it up so you can push directly if you like. The next steps are updating the tlm/deps/packages/CMakeLists.txt with the new SHA and bump the patch number. If this is only for FreeBSD (an unsupported platform), that's the end. If we need to rebuild these deps on supported platforms, we can do that and then update tlm/deps/manifest.cmake to introduce the new packages into the build.

**Comment by avsej** [comment]
Yes, I'm doing last-time check. But I won't use SHA1 for FreeBSD when it would be merged, all platforms will use the same branch.

**Comment by avsej** [comment]
@ceejatec http://review.couchbase.org/66789

**Comment by ceejatec** [comment]
Just to be sure: this change here is complete and ready to be merged?

**Comment by avsej** [comment]
Yes

**Pull request merged**
